apiVersion: v1
kind: ConfigMap
metadata:
  name: gbms-config
  namespace: gbms
data:
  gbms.entityEngine.dbPlatform: "mysql"
  gbms.entityEngine.dbHost: "192.168.100.235"
  gbms.entityEngine.dbPort: "3306"
  gbms.entityEngine.ofbizDbName: "gbms"
  gbms.entityEngine.olapDbName: "gbmsolap"
  gbms.entityEngine.tenantDbName: "gbmstenant"
  gbms.entityEngine.dbUser: "root"
  gbms.entityEngine.dbPassword: "root"
  gbms.security.hostHeadersAllowed: "dev.localkubernetes.com"
  gbms.jndi.javaNamingProviderUrl: "tcp://activemq-service:61616"