apiVersion: v1
kind: ConfigMap
metadata:
  name: gbms-config
  namespace: gbms
data:
  gbms.entityEngine.dbPlatform: "mysql"
  gbms.entityEngine.dbHost: "192.168.100.235"
  gbms.entityEngine.dbPort: "3306"
  gbms.entityEngine.ofbizDbName: "gbms"
  gbms.entityEngine.olapDbName: "gbmsolap"
  gbms.entityEngine.tenantDbName: "gbmstenant"
  gbms.entityEngine.dbUser: "root"
  gbms.entityEngine.dbPassword: "root"
  gbms.security.hostHeadersAllowed: "dev.localkubernetes.com"
  gbms.jndi.javaNamingProviderUrl: "tcp://activemq-service:61616"
  uilab.domainName: "k8s.master.gbms.cloudlakenet.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: gbms
data:
  metabase.dbPlatform: "mysql"
  metabase.dbHost: "rm-8vb42j29t1v5n2h2r.mysql.zhangbei.rds.aliyuncs.com"
  metabase.dbPort: "3306"
  metabase.dbName: "metabase"
  metabase.dbUser: "metabase"
  metabase.dbPassword: "Metabase@123"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dracula-config
  namespace: gbms
data:
  dracula.entityEngine.dbHost: rm-8vb42j29t1v5n2h2r.mysql.zhangbei.rds.aliyuncs.com
  dracula.entityEngine.dbPassword: lhDHeL5D%uG7sfew
  dracula.entityEngine.dbPlatform: mysql
  dracula.entityEngine.dbPort: '3306'
  dracula.entityEngine.dbUser: dracula
  dracula.entityEngine.ofbizDbName: dracula
  dracula.entityEngine.olapDbName: dracula_olap
  dracula.entityEngine.tenantDbName: dracula_tenant
  dracula.jndi.javaNamingProviderUrl: 'tcp://activemq-service:61616'
  dracula.security.hostHeadersAllowed: dracula.k8s.master.gbms.cloudlakenet.com